return {
	MiddlePodium = {
		DisplayName = "Bloodvein Horns",
		ClaimMessage = "Claimed Bloodvein Horns!",
		AlreadyClaimedMessage = "You already claimed this.",
		SoldOutMessage = "Sold Out",
		MainColor = Color3.fromRGB(156, 41, 49),
		SoldOutColor = Color3.fromRGB(255, 90, 90),
		MaxStock = 25,
		UGCAssetId = "117541224398731",
		GamepassId = "1347782133",
        ModifierText = "⭐ NEW LIMITED ⭐", -- or "NEW!", "LIMITED", etc.
        ModifierColor = Color3.fromRGB(255, 90, 90),
        ModifierOutline = Color3.fromRGB(40, 20, 0),
	},
	Podium1 = {
		DisplayName = "Gold Floating Crown",
		ClaimMessage = "Purchased Gold Floating Crown!",
		AlreadyClaimedMessage = "You already own this.",
		MainColor = Color3.fromRGB(207, 163, 32),
		SoldOutColor = Color3.fromRGB(255, 90, 90),
		MaxStock = 1,
		UGCAssetId = "97710718422536"
	},
	Podium6 = {
		DisplayName = "Fedora of the Darkest Night",
		ClaimMessage = "Claimed Fedora of the Darkest Night!",
		AlreadyClaimedMessage = "You already claimed this.",
		SoldOutMessage = "Sold Out",
		MainColor = Color3.fromRGB(144, 144, 219),
		SoldOutColor = Color3.fromRGB(255, 90, 90),
		MaxStock = 1,
		UGCAssetId = "102088540585401",
		GamepassId = "1330494489"
	},
}
